version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html

  portfolio:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./www/portfolio:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=portfolio.localhost
    depends_on:
      - nginx-proxy

volumes:
  html: